### ISSUE TITLE
ActionController::UnknownFormat - ActionController::UnknownFormat

### ISSUE THREAD

**Issue by brianllamar** [danielfone/as_csv#5]
I am attempting to use this gem but getting an UnknownFormat error.

Are there steps I missed in configuring my app to use the gem?

```ruby
# Enrollment Controller
  def roster
    respond_to do |format|
      format.csv { render csv: enrollments }
    end
  end

# Enrollment Model
def as_csv(options = {})
    attributes
end
```

I also have a serializer exposing attributes for enrollments, just trying to brain storm on next steps in debugging this. Any thoughts?

**Comment by danielfone** [comment]
Hi @brianllamar. I'll need a little more info to help. Can you paste the full backtrace into a gist and link it here please?

**Comment by brianllamar** [comment]
thanks, no worries if nothing stands out. I am still actively debugging this. 
https://gist.github.com/brianllamar/ed1fe69e7037ecc401ca

**Comment by danielfone** [comment]
Are you using `responds_to` in either the `EnrollmentsController` or `ApplicationController`?

**Comment by brianllamar** [comment]
I am using it in the roster method shown in my example, I also have at the top of the file 
```
respond_to :json, :csv
```

**Comment by danielfone** [comment]
Ok, it's hard to tell without debugging the app itself, but it looks like rails is processing that request as HTML. Unless there's something happening in your routes.rb, there's no indication that it should process

> GET /enrollments/roster?detail=roster&filters=%7B%22statuses%22%3A%5B%22current%22%5D%2C%22courses%22%3A%5B%22android%22%5D%7D&start=0 HTTP/1.1

as a CSV. If change that to `/enrollments/roster.csv?detail=....&start=0`, does it work?

**Comment by brianllamar** [comment]
WOW, that was it. no error. Kind of shocked I missed that but thanks for the second pair of eyes

**Comment by danielfone** [comment]
No worries!
