### ISSUE TITLE
rais exception of missing template

### ISSUE THREAD

**Issue by nasirshamshadsynnapps** [danielfone/as_csv#7]
I've added gem in my Gemfile 
bundled new gems

Added method in my controller
`def export_csv    
    respond_to do |format|
      format.csv do
        format.csv { render csv: Widget.all }
      end
    end
  end`

But when I open localhost:3000/export_csv.csv it returns this error 

Missing template whatwebs/export_csv, application/export_csv with {:locale=>[:en], :formats=>[:csv], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:
  * "/home/anasir/MyWork/scrapetag/app/views"
  * "/home/anasir/.rvm/gems/ruby-2.3.1@scrapetag/gems/devise-4.2.0/app/views"

**Comment by nasirshamshadsynnapps** [comment]
I've nested format 
Before 
respond_to do |format| 
       format.csv do 
            format.csv { render csv: Widget.all } 
        end 
  end

After removing inner It works like charm
respond_to do |format|
      format.csv { render csv: Whatweb.all }
end

**Comment by danielfone** [comment]
@nasirshamshadsynnapps glad you figured it out. The later is the recommended method documented in the README.
